#!/usr/bin/env bash
# A script that looks up DNS records of a passed domain

domain_config (){
    var1=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $var1" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  domain_config "$1" "www"
  domain_config "$1" "lb-01"
  domain_config "$1" "web-01"
  domain_config "$1" "web-02"
elif [ "$#" == 2 ]
then
  domain_config "$1" "$2"
fi
