#!/usr/bin/env bash
# script to install nginx and make return a page with a string 'Hello World'

sudo apt-get update
sudo apt-get -y install nginx

mkdir /var/www/html
touch /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm index.nginx-debian.html;
}
" > /var/www/html/sites-available/default

sudo service nginx start
