#!/usr/bin/env bash
# script to install nginx and then return a page with a string 'Hello World'
# We are make sure that the '/redirect_me' url is a permanent redirect

apt-get install -y nginx

mkdir /var/www/html
touch /var/www/html/index.nginx-debian.html
echo "Hello World" > /var/www/html/index.nginx-debian.html

var_line="rewrite ^/redirect_me$ https://www.google.com permanent;"
sed -i "53 i $var_line" /etc/nginx/sites-available/default

service nginx start
