#!/usr/bin/env bash
# script to install nginx and then return a page with a string 'Hello World'
# We are make sure that the '/redirect_me' url is a permanent redirect

sudo apt-get update
sudo apt-get install -y nginx

sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
REDIRECT_LINK="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "30i $REDIRECT_LINK" /etc/nginx/sites-available/default

sudo service nginx start
