#!/usr/bin/env bash
# script to install nginx and then return a page with a string 'Hello World'
# We are make sure that the '/redirect_me' url is a permanent redirect

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

# var_line="rewrite ^/redirect_me$ https://www.google.com permanent;"

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx start
