#!/usr/bin/env bash
# a script to install nginx and then return a page with a string 'Hello World'

sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" > /var/www/html/index.html

# Perform "permanent redirection" (301)
string1="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/itsoluwatobby permanent;"

sudo sed -i "s/server_name _;/$string1/" /etc/nginx/sites-enabled/default

# creating custom 404 error
echo "Ceci n'est pas une page" > sudo tee /var/www/html/404.html
string2="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string2/" /etc/nginx/sites-enabled/default

# Testing for syntax errors
sudo nginx -t

# restart nginx to effect changes
sudo service nginx reload
