#!/usr/bin/env bash

# a script to install nginx and then return a page with a string 'Hello World'
# We are to make sure that the '/redirect_me' url is a permanent redirect

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" > /etc/nginx/html/index.html

line1="\\\trewrite ^/redirect_me$ https://www.google.com permanent"
line2="\n\\terror_page 404 /404.html;\n\tlocation = /var/www/html/404.html {\n\t\tinternal;\n\t}"
PATTERN="#error_page 404 /404.html;"

sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo sed -i "30i $line1" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo sed -i "47i\ $PATTERN$line2" /etc/nginx/sites-available/default

sudo service nginx restart
sudo service nginx reload
