#!/usr/bin/env bash

# a script to install nginx and then return a page with a string 'Hello World'
# We are to make sure that the '/redirect_me' url is a permanent redirect

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

#line1="rewrite ^/redirect_me$ https://www.google.com permanent"
#line2="rewrite ^/redirect_me/$ https://www.google.com permanent"

echo "Ceci n'est pas une page" >> /etc/nginx/html/error_404.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx start
