#!/usr/bin/env bash
# Configures a new server to return a custom header

sudo apt-get -y update
sudo apt-get -y install nginx

# Create an index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Perform a "permanent redirection" (301)
string1="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/itsoluwatobby permanent;"
sudo sed -i "s/server_name _;/$string1/" /etc/nginx/sites-enabled/default

# Create a 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string2="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string2/" /etc/nginx/sites-enabled/default

# Create an HTTP response header
str="add_header X-Served-By $HOSTNAME;"

sudo sed -i "/server_name _/$str" /etc/nginx/sites-enabled/default

# restart nginx
sudo service nginx reload
