#!/usr/bin/env bash
# Install and configure HAProxy

sudo apt-get update -y
sudo apt-get install -y haproxy

echo "ENABLED=1" >> sudo /etc/default/haproxy

echo "
frontend itsoluwatobby_frontend
    bind *:80
    mode http
    default_backend itsoluwatobby_backend

backend itsoluwatobby_backend
    balance roundrobin
    server 357222-web-01 54.146.94.114 check port 80
    server 357222-web-02 54.172.58.174 check port 80
" >> /etc/haproxy/haproxy.cfg

# Testing HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# restart to effect changes
sudo service haproxy restart
