#!/usr/bin/env bash
# script to login into lb-01 nginx server

# setting up ssh agent
eval $("ssh-agent")

# declare my custom path to IdentityFile
ssh-add ~/.ssh/school

# username and IP address
ssh ubuntu@100.25.23.55

