#!/usr/bin/env bash
# find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
# Requirements:
#	* Nginx must be running, and listening on port 80 of all the
# 	server’s active IPv4 IPs
#	* Write a Bash script that configures a server to the above
#	requirements

string1="8080"
new_string1="80"

sed -i "s/$string1/$new_string1/g" /etc/nginx/sites-enabled/default

# restart nginx to effect changes
sudo service nginx restart
