#!/usr/bin/env bash
# find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80

# remove the default nginx sites-enabled file
rm /etc/nginx/sites-enabled/default

# create a symbolic link and listen on port 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
