#!/usr/bin/env bash
# create a symbolic link and listen on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
rm /var/run/nginx.pid
# kill "$(pgrep 'nginx' | head -1)"
