#!/usr/bin/env bash
# make it short and sweet

# create a symbolic link and listen on port 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# restart nginx to effect changes
sudo service nginx restart
# kill the first nginx instance
kill "$(pgrep 'nginx' | head -1)"
