#!/usr/bin/env bash
# This script displays numbers from 1 to 100 and:
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number. In a list format

text="Best School"
count=1

while [[ count -lt 101 ]]
do
	if [[ $((count%3)) == 0 && $((count%5)) == 0 ]]; then
		echo "FizzBuzz"
	elif [[ $((count%3)) == 0 ]]; then
		echo "Fizz"
	elif [[ $((count%5)) == 0 ]]; then
                echo "Buzz"
	else
		echo $count
	fi
	count=$((count+1))
done
