#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but for
# the 9th iteration displays Best School and then Hi on a new linw

text="Best School"
count=0

while [[ count -lt 10 ]]
do
	echo $text
	if [[ count -eq 8 ]]; then
		echo Hi
	fi
	count=$((count+1))
done
