#!/usr/bin/env bash
# This script loops from 1 - 10
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

text="Best School"
count=0

while [[ count -lt 10 ]]
do
	if [[ count -eq 3 ]]; then
		echo "bad luck"
	elif [[ count -eq 7 ]]; then
		echo "good luck"
	else
		echo $text
	fi
	count=$((count+1))
done
