#!/usr/bin/env bash
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# Write a Bash script that configures the container to fit the above requirements

pkill apache2
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chown -R nginx:nginx /etc/nginx/ /var/log/nginx/ 
chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
