#!/usr/bin/env bash
# nginx server configuration, configure to take even or odd number routes

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name 54.146.94.114;

    add_header X-Served-By 357222-web-01;

    # serve /airbnb-onepage/ route
    location = /airbnb-onepage/ {
    	proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
    }

    # serve /number_odd_or_even/ route on Airbnb_clone_v2
    location ~ ^/airbnb-dynamic/number_odd_or_even/(\d+)$ {
    	proxy_pass http://127.0.0.1:5001/number_odd_or_even/$1;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}
