#!/usr/bin/env bash
# nginx server configuration for AirBnB_clone_v3

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # use IP of server as the domain server_name
    server_name 54.146.94.114;

    add_header X-Served-By 357222-web-01;

    # serve /airbnb-onepage/ route
    location = /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
    }

    # serve /number_odd_or_even/ route on Airbnb_clone_v2
    location ~ ^/airbnb-dynamic/number_odd_or_even/(\d+)$ {
        proxy_pass http://127.0.0.1:5001/number_odd_or_even/$1;
    }

    # serve AirBnB_clone_v3 on /api route
    location /api/ {
        proxy_pass http://127.0.0.1:5002;
    }

    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}
